---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
# permalink: / ## disables post output
permalink: /blog/:year/:month/:title
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "lawberry"
keywords:    "lawberry, legal service, virtual inhouse"
description: "lawberry - an affordable legal service"
source_link: "https://github.com/lawberry/lawberry"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)

post:
  template: _post.txt
  extension: md

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

collections:
  front:
    output: false
